### PR TITLE
fix: don't check for check compliance settings for s3 config

### PR DESCRIPTION
**Pull request by fmartingr**
#### Summary
The compliance check was fixed in the code to `false`, this PR removes the current compliance configuration from the system and just follows the configuration provided in the system console.

#### Ticket Link
https://mattermost.atlassian.net/browse/MM-59831

### CODE REVIEW

**Review by esarafianou — CHANGES_REQUESTED** [review]
@fmartingr  Why does the Compliance Monitoring option in System Console affect whether SSE in S3 will be enabled or not? 

Unless I'm missing something, this seems irrelevant to me. If I select `True` in the AmazonSSE setting in legal hold config, that should hold true regardless of the compliance monitoring option

**Comment by fmartingr** [comment]
> @fmartingr Why does the Compliance Monitoring option in System Console affect whether SSE in S3 will be enabled or not?
> 
> Unless I'm missing something, this seems irrelevant to me. If I select `True` in the AmazonSSE setting in legal hold config, that should hold true regardless of the compliance monitoring option

I was maintaining the same logic there was, just retrieving the appropriate configuration from the system console instead of using fixed values.

In my head, it should be enabled if: 
- I enable it in the settings (regardless of compliance)
- Compliance is enabled (regardless of the setting)

**Comment by fmartingr** [comment]
Made some changes regarding my previous comment.

**Comment by esarafianou** [comment]
@fmartingr It's still not clear to me why enabling compliance has anything to do with enabling AWS SS3 SSE.

**Comment by fmartingr** [comment]
> @fmartingr It's still not clear to me why enabling compliance has anything to do with enabling AWS SS3 SSE.

cc: @wiggin77

**Comment by wiggin77** [comment]
> I was maintaining the same logic there was,

@fmartingr could you elaborate on that?  I'm not seeing where compliance monitoring appears in the original S3 bucket config code.

**Comment by fmartingr** [comment]
> > I was maintaining the same logic there was,
> 
> @fmartingr could you elaborate on that? I'm not seeing where compliance monitoring appears in the original S3 bucket config code.

The og line of code was: `fileSettings.AmazonS3SSE != nil && *fileSettings.AmazonS3SSE && enableComplianceFeature`

What is `enableCompilanceFeature` refers to? I though it was compliance from the system setting.

**Comment by wiggin77** [comment]
> What is `enableComplianceFeature` refers to?

I don't know what the author intended there other than it is used to turn off server side encryption even when it is requested in the config.  I think we should eliminate the `enableComplianceFeature` parameter altogether.

**Review by esarafianou — APPROVED** [review]
Thanks Felipe!

**Comment by wiggin77** [comment]
@fmartingr we also have skip-verify always hard-coded to true.  Wondering if we should expose that in the config, and what the performance hit it.  Thoughts?  cc @esarafianou

**Comment by fmartingr** [comment]
> @fmartingr we also have skip-verify always hard-coded to true. Wondering if we should expose that in the config, and what the performance hit it. Thoughts? cc @esarafianou

I though it was something related to S3 but it seems it is to verify the ssl connection or not. This seems like a mistake used for local development, unsure if we should disable it (always verify) considering the implications of this plugin. For local development we could always tune that manually.

**Comment by esarafianou** [comment]
@fmartingr the SSL connection between which points? 

Looking at the `mattermost` repo, we always default to `false` there too: 

Used here as a 3rd argument: https://github.com/mattermost/mattermost/blob/3acceeefb21bba18c94a87bf365348dbec7dd85d/server/platform/shared/filestore/filesstore.go#L93

Called here with `false`: 
* https://github.com/mattermost/mattermost/blob/3acceeefb21bba18c94a87bf365348dbec7dd85d/server/channels/app/file.go#L61-L64
* https://github.com/mattermost/mattermost/blob/3acceeefb21bba18c94a87bf365348dbec7dd85d/server/channels/app/platform/service.go#L281

**Comment by fmartingr** [comment]
> @fmartingr the SSL connection between which points?

The application and the S3-compatible server.

> Looking at the `mattermost` repo, we always default to `false` there too:
> 
> Used here as a 3rd argument: https://github.com/mattermost/mattermost/blob/3acceeefb21bba18c94a87bf365348dbec7dd85d/server/platform/shared/filestore/filesstore.go#L93
> 
> Called here with `false`:
> 
> * https://github.com/mattermost/mattermost/blob/3acceeefb21bba18c94a87bf365348dbec7dd85d/server/channels/app/file.go#L61-L64
> * https://github.com/mattermost/mattermost/blob/3acceeefb21bba18c94a87bf365348dbec7dd85d/server/channels/app/platform/service.go#L281

Yeah, but we have it fixed to `true`, meaning we will skip SSL verification:

https://github.com/mattermost/mattermost/blob/3acceeefb21bba18c94a87bf365348dbec7dd85d/server/platform/shared/filestore/s3store.go#L167-L169

https://pkg.go.dev/crypto/tls@go1.23.1#InsecureCipherSuites
```
	// InsecureSkipVerify controls whether a client verifies the server's
	// certificate chain and host name. If InsecureSkipVerify is true, crypto/tls
	// accepts any certificate presented by the server and any host name in that
	// certificate. In this mode, TLS is susceptible to machine-in-the-middle
	// attacks unless custom verification is used. This should be used only for
	// testing or in combination with VerifyConnection or VerifyPeerCertificate.
```

**Comment by BenCookie95** [comment]
> > @fmartingr we also have skip-verify always hard-coded to true. Wondering if we should expose that in the config, and what the performance hit it. Thoughts? cc @esarafianou
> 
> I though it was something related to S3 but it seems it is to verify the ssl connection or not. This seems like a mistake used for local development, unsure if we should disable it (always verify) considering the implications of this plugin. For local development we could always tune that manually.

Yeah I think we should just hardcode the value to `false`, I don't think we need a config for that. We don't expose a config for that in Mattermost either

**Comment by fmartingr** [comment]
Just hardcoded it to false, to be explicit, since that makes more sense. 👍

**Review by BenCookie95 — APPROVED** [review]

**Review by wiggin77 — APPROVED** [review]

**Comment by esarafianou** [comment]
@fmartingr can you point me where you saw that the `skipVerify` is for local development only?

**Comment by fmartingr** [comment]
> @fmartingr can you point me where you saw that the `skipVerify` is for local development only?

Is not something I saw, it was just a guess.

**Comment by AayushChaudhary0001** [comment]
@fmartingr  I tested this PR and its working properly by if am testing a build before this PR, the build is not getting stored in the S3 bucket on clicking the download button. May I know what actually does this PR do and what do I need to test?

**Comment by fmartingr** [comment]
This PR only changes the compilance configuration, but this has been removed in #116 so I urge you to QA that one directly.

**Pull request merged**
