### PR TITLE
Properly update and process hashes file

### PR DESCRIPTION
**Pull request by fmartingr**
#### Summary

This fixes two issues:

- First one in the processor: The file being opened wasn't the one that required hashing. (introduced in #101)
- Second in the job system: The hash file was being used append only, meaning that we get a new `path,hash` file for the same file every loop of the processor. Now we open the file, check if the path exists and update its hash.
- **Breaking**: Changed the hashes file type from CSV to JSON.

##### Basic test scenario

1. Deploy this version of the plugin
2. Create a legal hold that contains users that have posted data in the past
3. Run the legal hold job manually by using #43 (wait for process to finish depending on dataset, check logs)
4. Download the legal hold bundle for this entry
5. Run the processor over it with the `--legal-hold-secret` flag set. You can retrieve the secret from the plugin settings in the system console, the button to the left of the download button.
6. Ensure file verification steps are happening

### CODE REVIEW

**Review by BenCookie95 — APPROVED** [review]
LGTM. Something for a later date but it would be good if we could add tests for this.

**Comment by fmartingr** [comment]
@BenCookie95 I refactored the file from CSV to JSON to make it easier to handle, please check this: 636e8bb30b9f4463d60ec220d3ea92b577fb5338

**Review by BenCookie95 — APPROVED** [review]
LGTM, JSON is much easier to follow

**Comment by AayushChaudhary0001** [comment]
@fmartingr I was testing this PR against the build from this branch for the processor tool legal hold secret flag, I am facing an issue here. If I enter any invalid legal hold secret, the csv file is processed and get converted to html file, which should not be the ideal case. If the secret does not matches, then the files should not be processed. Please see the screenshots below:-

image


image

**Comment by fmartingr** [comment]
> @fmartingr I was testing this PR against the build from this branch for the processor tool legal hold secret flag, I am facing an issue here. If I enter any invalid legal hold secret, the csv file is processed and get converted to html file, which should not be the ideal case. If the secret does not matches, then the files should not be processed. Please see the screenshots below:-
> 
> image
> 
> image

Yeah, you should have a message above stating that the validation didn't pass, but files get converted either way.

**Comment by AayushChaudhary0001** [comment]
@fmartingr I got this message while the files were getting converted

image


I think, if the secret mismatches, the files should not get converted ideally.

**Comment by fmartingr** [comment]
> @fmartingr I got this message while the files were getting converted
> 
> image
> 
> I think, if the secret mismatches, the files should not get converted ideally.

Yeah I think you are right, I just made the change. I already thought that the verification output was a bit lost among all the output that happens below, barely noticeable. 👍

**Review by wiggin77 — APPROVED** [review]

**Comment by fmartingr** [comment]
@AayushChaudhary0001 is this good to go?

**Comment by AayushChaudhary0001** [comment]
Hey @fmartingr , I have tested this PR against the issue logged above, the secret if entered invalid does not work and shows the error and files did not get process. This is the correct behaviour and the PR is working fine for this, LGTM. Approved.

**Review by AayushChaudhary0001 — APPROVED** [review]

**Pull request merged**
